### ISSUE TITLE
Hardcoded ALLOWED_HOSTS with localhost may be a potential security issue

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycon.tw#792]
We have landed https://github.com/pycontw/pycon.tw/pull/783 but this line may be risky https://github.com/pycontw/pycon.tw/blob/master/src/pycontw2016/settings/base.py#L72 I checked our production and staging site by following this comment https://stackoverflow.com/a/30579484/3517665 and think it is be good/safe for us at this moment. 

```
$ curl -I pycon.tw
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.15.12
Date: Thu, 04 Jun 2020 14:38:03 GMT
Content-Type: text/html
Content-Length: 146
Location: https://tw.pycon.org/
Via: 1.1 google


$ curl -I staging.pycon.tw
HTTP/1.1 301 Moved Permanently
Server: nginx/1.15.12
Date: Thu, 04 Jun 2020 14:49:08 GMT
Content-Type: text/html
Content-Length: 170
Connection: keep-alive
Location: https://staging.pycon.tw/
```

However, in case in the future someone give too much permission in the http header (see this comment https://stackoverflow.com/a/30579484/3517665 ), I would suggest let's move the hard-coded localhost address to be a configuration file or environment variable instead.

## Describe the solution you'd like
Use a configuration file or environment variable

## Describe alternatives you've considered
ALLOWED_HOSTS = ['127.0.0.1'] may or may not be an alternative. (further evaluation needed)

**Comment by tai271828** [comment]
@mattwang44 are you interested in working on this issue? @uranusjr  do you think of any potential security issue regarding this issue (hard coded local host address), or suggest any solution?

**Comment by uranusjr** [comment]
IIRC the loose `ALLOWED_HOSTS` value is needed for Docker deployment (unless you want to set up complicated Docker networking things). I am OK if you want to change that though, just want to warn you before you waste too much time on taming Docker.

**Comment by shunghsiyu** [comment]
Hmm...I just tried turning `ALLOWED_HOSTS` back into an empty list `[]`, creating `local.env` and then starting a development environment with `contrib/enter_dev_env.sh`. (I'm using Docker Desktop on Mac). And the access to the development environment at `localhost:8000` **still works**.

For me the `ALLOWED_HOSTS = ['0.0.0.0', 'localhost']` setting seems to only make a difference when I try to access the development environment using `0.0.0.0:8000`.

I think we can change `ALLOWED_HOSTS` back into an empty list if we don't mind loosing the access to development environment through `0.0.0.0:8000` (which IMHO is [not the best way](https://superuser.com/a/949522) to say "connect to the machine I'm using right now"), since [Django documentation stated that](https://docs.djangoproject.com/en/3.0/ref/settings/#allowed-hosts)

> When DEBUG is True and ALLOWED_HOSTS is empty, the host is validated against ['localhost', '127.0.0.1', '[::1]'].

Can @mattwang44 elaborate a bit on the comment `for connecting to db in dev env` at https://github.com/pycontw/pycon.tw/blob/a03d788/src/pycontw2016/settings/base.py#L72 just to make sure I'm not missing anything here?

**Comment by shunghsiyu** [comment]
As for the production environment, I think it is not affected by the setting in https://github.com/pycontw/pycon.tw/blob/master/src/pycontw2016/settings/base.py, because https://github.com/pycontw/pycon.tw/blob/master/src/pycontw2016/settings/production/base.py overrides the `ALLOWED_HOSTS` setting to the hard-coded `tw.pycon.org`.

No idea about the staging environment though.

**Comment by mattwang44** [comment]
Yes, you're right! I use `0.0.0.0:8000` when implementing #783 and just blindly thought it won't work for `localhost:8000` too. Would you mind sending a PR for clearing the `ALLOWED_HOSTS` and the following meaningless comment? Thanks again for your efforts!

**Comment by shunghsiyu** [comment]
> Would you mind sending a PR for clearing the `ALLOWED_HOSTS` and the following meaningless comment? Thanks again for your efforts!

No problem, PR sent ☺️. Thank you!
