### ISSUE TITLE
[Feature Request] Event detail page should display location and time slot

### ISSUE THREAD

**Issue by uranusjr** [pycontw/pycon.tw#915]
2019:

![Screenshot 2020-08-31 at 15 00 29](https://user-images.githubusercontent.com/605277/91691773-ccb31200-eb9a-11ea-8db1-36c07dd29a5e.png)

2020:

![Screenshot 2020-08-31 at 15 01 00](https://user-images.githubusercontent.com/605277/91691790-d2a8f300-eb9a-11ea-934c-3d8594f84d91.png)

This applies to all talk, tutorial, and community track events.

**Comment by yychen** [comment]
oh yes! I hide it when the list is out, but before the detail schedule. Forgot to put the information back.

**Comment by yychen** [comment]
After deployment, I found out that Community Track talks won't show this detail. It is because the talks in community track is implemented differently. A community track talk does not have a ProposedTalkEvent record, and they don't show up in the schedule. Maybe we can do this in the CommunityTrackEvent.

**Comment by yychen** [comment]
> 
> 
> After deployment, I found out that Community Track talks won't show this detail. It is because the talks in community track is implemented differently. A community track talk does not have a ProposedTalkEvent record, and they don't show up in the schedule. Maybe we can do this in the CommunityTrackEvent.

This is also being taken care of in #921
